### ISSUE TITLE
大佬有考虑过用github action去执行吗

### ISSUE THREAD

**Issue by ajiangstudy** [Qliangw/notion_sync_data#19]
自己写了个脚本，发现有几个问题
1. auto.yaml每次生成会重复生成数据库页面，只能通过手动上传auto.yaml跳过初始化（我的想法是直接初次运行时候可以保存到/doc/目录下，下次执行自动跳过自检，但是不太会整
2. 可以将参数更改{{secert.NOTION_TOKEN}}这类吗，这样是否开源更方便，更易用（当然大佬的gui也更方便
只是个人建议，感谢大佬开发出这个逃离计划！
```
name: douban
on:
  workflow_dispatch:
  schedule: 
    # 代表国际标准时间4点0分，北京时间需要+8小时，代表北京时间中午12点运行
    - cron: '0 0 * * *'
jobs:
#将工作流程中运行的所有作业组合在一起
  build:
  #定义名为 build 的作业。 子键将定义作业的属性 
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
    
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.1
      - name: install pip packages
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt
      - name: sync
        run: |
          python run.py -f init
          python run.py -m movie -s all
          python run.py -m book -s all
          python run.py -m music -s all
```
